# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔
  小玩意: /game
  关于我: /about

rss: /atom.xml

social:
  zhihu: https://www.zhihu.com/people/hu-chun-wang
  facebook: https://www.facebook.com/profile.php?id=100006547240957
  github: https://github.com/adspoing

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

#Personal
avatar: "http://ww3.sinaimg.cn/large/006fgruwgw1f28iqa0ke6j308x08xweg.jpg"

